# Additional materials and help {#sec-si}

## Additional materials

- The [Single-cell proteomics data analysis using `QFeatures` and
  `scp`](https://lgatto.github.io/QFeaturesScpWorkshop2021/) workshop
  is provided as two vignettes. The first one provides a general
  introduction to the `QFeatures` class in the general context of mass
  spectrometry-based proteomics data manipulation. The second vignette
  focuses on single-cell application and introduces the `scp` package
  [@Vanderaa:2021] as an extension of `QFeatures`. This second
  vignette also provides exercises that give the attendee the
  opportunity to apply the learned concepts to reproduce a published
  analysis on a subset of a real data set.

- The [SpectraTutorials](https://jorainer.github.io/SpectraTutorials) package
  provides three different vignettes:
  - [Seamless Integration of Mass Spectrometry Data from Different
  Sources](https://jorainer.github.io/SpectraTutorials/articles/analyzing-MS-data-from-different-sources-with-Spectra.html):
  describes import/export of MS data from/to files in different format as well
  as processing and handling of MS data with the *Spectra* package.
  - [Spectra: an Expandable Infrastructure to Handle Mass Spectrometry
  Data](https://jorainer.github.io/SpectraTutorials/articles/Spectra-backends.html):
  explains the concept of backends in *Spectra*, their properties, use cases
  along with performance considerations.
  - [MS/MS Spectra Matching with the MetaboAnnotation
  Package](https://jorainer.github.io/SpectraTutorials/articles/Spectra-matching-with-MetaboAnnotation.html):
  explains how the *Spectra* package can be used together with the `r
  BiocStyle::Biocpkg("MetaboAnnotation")` package in LC-MS/MS annotation
  workflows for untargeted metabolomics data.

- A tutorial presenting [Use Cases and Examples for Annotation of
  Untargeted Metabolomics
  Data](https://jorainer.github.io/MetaboAnnotationTutorials/) using
  the `MetaboAnnotation` and `MetaboCoreUtils` packages
  [@Rainer:2022].

- [Exploring and analyzing LC-MS data with Spectra and
  xcms](https://jorainer.github.io/xcmsTutorials/) provides an
  overview of recent developments in Bioconductor to work with mass
  spectrometry
  ([MsExperiment](https://github.com/RforMassSpectrometry/MsExperiment),
  [Spectra](https://github.com/RforMassSpectrometry/Spectra)) and
  specifically LC-MS data ([xcms](https://github.com/sneumann/xcms))
  and walks through the preprocessing of a small data set emphasizing
  on selection of data-dependent settings for the individual
  pre-processing steps.

## Questions and help

For questions about specific software or their usage, please refer to
the software's github issue page, or use the [Bioconductor support
site](http://support.bioconductor.org/).
